# Generated by Django 4.2.23 on 2025-06-20 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='权限名称')),
                ('codename', models.CharField(max_length=100, unique=True, verbose_name='权限代码')),
                ('permission_type', models.CharField(choices=[('supply', '耗材管理'), ('inventory', '库存管理'), ('user', '用户管理'), ('system', '系统管理'), ('report', '报表管理')], max_length=20, verbose_name='权限类型')),
                ('description', models.TextField(blank=True, verbose_name='权限描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '权限',
                'verbose_name_plural': '权限',
                'ordering': ['permission_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('admin', '管理员'), ('user', '普通用户'), ('manager', '经理'), ('operator', '操作员')], max_length=20, unique=True, verbose_name='角色名称')),
                ('description', models.TextField(blank=True, verbose_name='角色描述')),
                ('permissions', models.JSONField(default=list, verbose_name='权限列表')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '用户角色',
                'verbose_name_plural': '用户角色',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='部门')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='职位')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='电话')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='最后登录IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.userrole', verbose_name='用户角色')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('create', '创建'), ('update', '更新'), ('delete', '删除'), ('view', '查看'), ('login', '登录'), ('logout', '登出'), ('export', '导出'), ('import', '导入')], max_length=20, verbose_name='操作类型')),
                ('model_name', models.CharField(max_length=100, verbose_name='模型名称')),
                ('object_id', models.CharField(blank=True, max_length=100, verbose_name='对象ID')),
                ('description', models.TextField(verbose_name='操作描述')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, verbose_name='用户代理')),
                ('request_data', models.JSONField(blank=True, default=dict, verbose_name='请求数据')),
                ('response_data', models.JSONField(blank=True, default=dict, verbose_name='响应数据')),
                ('status_code', models.IntegerField(default=200, verbose_name='状态码')),
                ('execution_time', models.FloatField(default=0.0, verbose_name='执行时间(秒)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作用户')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'operation_type'], name='accounts_op_user_id_69e7bc_idx'), models.Index(fields=['model_name', 'object_id'], name='accounts_op_model_n_f87bde_idx'), models.Index(fields=['created_at'], name='accounts_op_created_8c1de8_idx')],
            },
        ),
    ]
