# Generated by Django 5.2.3 on 2025-06-20 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='菜单名称')),
                ('path', models.CharField(blank=True, max_length=200, verbose_name='路由路径')),
                ('component', models.CharField(blank=True, max_length=200, verbose_name='组件路径')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='图标')),
                ('menu_type', models.CharField(choices=[('menu', '菜单'), ('page', '页面'), ('button', '按钮')], default='menu', max_length=20, verbose_name='菜单类型')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_visible', models.BooleanField(default=True, verbose_name='是否可见')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounts.menu', verbose_name='父菜单')),
                ('permissions', models.ManyToManyField(blank=True, to='accounts.permission', verbose_name='所需权限')),
                ('roles', models.ManyToManyField(blank=True, to='accounts.userrole', verbose_name='可访问角色')),
            ],
            options={
                'verbose_name': '菜单',
                'verbose_name_plural': '菜单',
                'ordering': ['order', 'id'],
                'unique_together': {('name', 'parent')},
            },
        ),
    ]
