# Generated by Django 4.2.23 on 2025-06-24 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='position',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
