# Generated by Django 4.2.23 on 2025-06-26 07:14

from django.db import migrations, models


def migrate_user_status(apps, schema_editor):
    """将现有的is_active字段迁移到新的status字段"""
    UserProfile = apps.get_model('accounts', 'UserProfile')
    
    for profile in UserProfile.objects.all():
        if profile.is_active:
            profile.status = 'active'
        else:
            profile.status = 'disabled'  # 将原来的非激活状态视为被禁用
        profile.save()


def reverse_migrate_user_status(apps, schema_editor):
    """反向迁移：从status字段恢复到is_active字段"""
    UserProfile = apps.get_model('accounts', 'UserProfile')
    
    for profile in UserProfile.objects.all():
        profile.is_active = (profile.status == 'active')
        profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_employee_id_to_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('active', '激活'), ('inactive', '未激活'), ('disabled', '被禁用')], default='inactive', max_length=20, verbose_name='用户状态'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否激活(已废弃)'),
        ),
        # 执行数据迁移
        migrations.RunPython(migrate_user_status, reverse_migrate_user_status),
    ]
