# Generated by Django 4.2.23 on 2025-06-20 01:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='耗材名称')),
                ('category', models.CharField(max_length=100, verbose_name='分类')),
                ('unit', models.CharField(max_length=50, verbose_name='单位')),
                ('current_stock', models.IntegerField(default=0, verbose_name='当前库存')),
                ('safety_stock', models.IntegerField(default=0, verbose_name='安全库存')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '耗材',
                'verbose_name_plural': '耗材',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='部门')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='职位')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='电话')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
        migrations.CreateModel(
            name='InventoryRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('in', '入库'), ('out', '出库'), ('adjust', '调整')], max_length=10, verbose_name='操作类型')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('operator', models.CharField(max_length=100, verbose_name='操作人')),
                ('department', models.CharField(max_length=100, verbose_name='部门')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('previous_stock', models.IntegerField(verbose_name='调整前库存')),
                ('new_stock', models.IntegerField(verbose_name='调整后库存')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplies.supply', verbose_name='耗材')),
            ],
            options={
                'verbose_name': '库存变动记录',
                'verbose_name_plural': '库存变动记录',
                'ordering': ['-timestamp'],
            },
        ),
    ]
