# Generated by Django 5.2.3 on 2025-06-21 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
