# Generated by Django 5.2.3 on 2025-06-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0002_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='lead_time_days',
            field=models.IntegerField(default=0, verbose_name='交货周期(天)'),
        ),
        migrations.AddField(
            model_name='supply',
            name='max_stock',
            field=models.IntegerField(default=0, verbose_name='最高库存'),
        ),
        migrations.AddField(
            model_name='supply',
            name='min_order_quantity',
            field=models.IntegerField(default=1, verbose_name='最小采购量(MOQ)'),
        ),
        migrations.AddField(
            model_name='supply',
            name='min_stock',
            field=models.IntegerField(default=0, verbose_name='最低库存'),
        ),
        migrations.AddField(
            model_name='supply',
            name='purchaser',
            field=models.CharField(default='', max_length=50, verbose_name='采购员'),
        ),
        migrations.AddField(
            model_name='supply',
            name='standard_usage_count',
            field=models.IntegerField(default=0, verbose_name='标准使用次数'),
        ),
        migrations.AddField(
            model_name='supply',
            name='usage_per_machine',
            field=models.IntegerField(default=0, verbose_name='每台机用量'),
        ),
        migrations.AddField(
            model_name='supply',
            name='usage_station',
            field=models.CharField(default='', max_length=100, verbose_name='使用站别'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='unit',
            field=models.CharField(max_length=20, verbose_name='单位'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价(RMB)'),
        ),
    ]
