# Generated by Django 4.2.23 on 2025-07-02 00:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supplies', '0004_capacityforecast_b482supplyitem_b453supplyitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationForm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='申请表名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='申请表代码')),
                ('department', models.CharField(max_length=100, verbose_name='申请部门')),
                ('period', models.CharField(max_length=50, verbose_name='申请周期')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '启用'), ('archived', '归档')], default='draft', max_length=20, verbose_name='状态')),
                ('calculation_form_id', models.IntegerField(blank=True, null=True, verbose_name='关联的计算表ID')),
                ('has_calculation_form', models.BooleanField(default=False, verbose_name='是否有关联的计算表')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建用户')),
            ],
            options={
                'verbose_name': '申请表',
                'verbose_name_plural': '申请表',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DynamicForecastData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='预测名称')),
                ('forecast_data', models.JSONField(default=dict, verbose_name='预测数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplies.applicationform', verbose_name='所属申请表')),
            ],
            options={
                'verbose_name': '动态产能预测数据',
                'verbose_name_plural': '动态产能预测数据',
                'ordering': ['form', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='模板名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='模板代码')),
                ('template_type', models.CharField(choices=[('supply_management', '耗材管控申请表'), ('demand_calculation', '需求计算表'), ('capacity_forecast', '产能预测表'), ('custom', '自定义表格')], max_length=50, verbose_name='模板类型')),
                ('description', models.TextField(blank=True, verbose_name='模板描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('has_calculation', models.BooleanField(default=False, verbose_name='是否包含计算功能')),
                ('calculation_template_id', models.IntegerField(blank=True, null=True, verbose_name='关联的计算模板ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建用户')),
            ],
            options={
                'verbose_name': '申请表模板',
                'verbose_name_plural': '申请表模板',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='applicationform',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplies.applicationtemplate', verbose_name='申请表模板'),
        ),
        migrations.CreateModel(
            name='DynamicSupplyItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('serial_number', models.IntegerField(verbose_name='序号')),
                ('material_description', models.TextField(verbose_name='物料描述')),
                ('unit', models.CharField(default='pcs', max_length=20, verbose_name='单位')),
                ('purchaser', models.CharField(max_length=50, verbose_name='采购员')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价(RMB)')),
                ('max_safety_stock', models.IntegerField(verbose_name='最高安全库存')),
                ('min_safety_stock', models.IntegerField(verbose_name='最低安全库存')),
                ('moq', models.IntegerField(verbose_name='最小采购量(MOQ)')),
                ('lead_time', models.IntegerField(verbose_name='L/T(Day)')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('monthly_data', models.JSONField(default=dict, verbose_name='月度数据')),
                ('usage_per_set', models.IntegerField(default=1, verbose_name='每套机用量')),
                ('usage_count', models.IntegerField(default=1000, verbose_name='使用次数')),
                ('monthly_capacity', models.IntegerField(default=497700, verbose_name='当月产能')),
                ('enable_auto_calculation', models.BooleanField(default=False, verbose_name='启用自动计算')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplies.applicationform', verbose_name='所属申请表')),
            ],
            options={
                'verbose_name': '动态申请表耗材项目',
                'verbose_name_plural': '动态申请表耗材项目',
                'ordering': ['form', 'serial_number'],
                'unique_together': {('form', 'serial_number')},
            },
        ),
        migrations.CreateModel(
            name='DynamicCalculationItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('no', models.IntegerField(verbose_name='No.')),
                ('material_name', models.CharField(max_length=200, verbose_name='料材名称')),
                ('usage_station', models.CharField(max_length=100, verbose_name='使用站别')),
                ('usage_per_set', models.IntegerField(verbose_name='每套机用量')),
                ('usage_count', models.IntegerField(verbose_name='使用次数')),
                ('monthly_capacity', models.IntegerField(verbose_name='当月产能')),
                ('min_stock', models.IntegerField(verbose_name='最低库存数量')),
                ('max_stock', models.IntegerField(verbose_name='最高库存数量')),
                ('monthly_demand', models.IntegerField(verbose_name='当月需求')),
                ('monthly_net_demand', models.IntegerField(verbose_name='当月网路需求')),
                ('actual_order', models.IntegerField(verbose_name='实际订购数量')),
                ('moq_remark', models.TextField(blank=True, verbose_name='备注(MOQ)')),
                ('linked_supply_item_id', models.IntegerField(blank=True, null=True, verbose_name='关联的管控表项目ID')),
                ('linked_material', models.TextField(blank=True, verbose_name='关联的物料描述')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='单价')),
                ('moq', models.IntegerField(blank=True, null=True, verbose_name='MOQ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplies.applicationform', verbose_name='所属申请表')),
            ],
            options={
                'verbose_name': '动态计算表项目',
                'verbose_name_plural': '动态计算表项目',
                'ordering': ['form', 'no'],
                'unique_together': {('form', 'no')},
            },
        ),
    ]
