# Generated by Django 4.2.23 on 2025-07-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0008_finalize_template_type_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamiccalculationitem',
            name='apr_2025_stock',
            field=models.IntegerField(default=0, verbose_name='2025年4月库存'),
        ),
        migrations.AddField(
            model_name='dynamiccalculationitem',
            name='aug_2025_demand',
            field=models.IntegerField(default=0, verbose_name='2025年8月需求'),
        ),
        migrations.AddField(
            model_name='dynamiccalculationitem',
            name='current_stock_0619',
            field=models.IntegerField(default=0, verbose_name='2025/6/19库存数量'),
        ),
        migrations.AddField(
            model_name='dynamiccalculationitem',
            name='current_stock_0625',
            field=models.IntegerField(default=0, verbose_name='2024/6/25库存数量'),
        ),
        migrations.AddField(
            model_name='dynamiccalculationitem',
            name='jul_2025_stock',
            field=models.IntegerField(default=0, verbose_name='2025年7月库存'),
        ),
        migrations.AddField(
            model_name='dynamiccalculationitem',
            name='jul_m01_demand',
            field=models.IntegerField(default=0, verbose_name='7月M01需求'),
        ),
        migrations.AddField(
            model_name='dynamiccalculationitem',
            name='jul_m02_demand',
            field=models.IntegerField(default=0, verbose_name='7月M02需求'),
        ),
        migrations.AddField(
            model_name='dynamiccalculationitem',
            name='jul_m03_demand',
            field=models.IntegerField(default=0, verbose_name='7月M03需求'),
        ),
        migrations.AddField(
            model_name='dynamiccalculationitem',
            name='jul_m04_demand',
            field=models.IntegerField(default=0, verbose_name='7月M04需求'),
        ),
        migrations.AddField(
            model_name='dynamiccalculationitem',
            name='jun_2025_demand',
            field=models.IntegerField(default=0, verbose_name='2025年6月需求'),
        ),
        migrations.AddField(
            model_name='dynamiccalculationitem',
            name='jun_2025_stock',
            field=models.IntegerField(default=0, verbose_name='2025年6月库存'),
        ),
        migrations.AddField(
            model_name='dynamiccalculationitem',
            name='may_2025_demand',
            field=models.IntegerField(default=0, verbose_name='2025年5月需求'),
        ),
        migrations.AddField(
            model_name='dynamiccalculationitem',
            name='may_2025_stock',
            field=models.IntegerField(default=0, verbose_name='2025年5月库存'),
        ),
        migrations.AddField(
            model_name='dynamiccalculationitem',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='总金额'),
        ),
        migrations.AlterField(
            model_name='applicationtemplate',
            name='template_type',
            field=models.JSONField(default=list, verbose_name='模板类型'),
        ),
    ]
