# Generated by Django 4.2.23 on 2025-07-03 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0009_add_monthly_inventory_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamiccalculationitem',
            name='purchaser',
            field=models.CharField(default='', max_length=50, verbose_name='采购员'),
        ),
    ]
