# Generated by Django 5.2.3 on 2025-08-04 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0010_add_purchaser_to_dynamic_calculation_item'),
    ]

    operations = [
        # 注意：PostgreSQL中无法直接修改字段的verbose_name，这需要在Django模型层面修改
        # 这个迁移文件主要用于记录变更，实际的verbose_name修改已经在模型中完成
    ]
