# Generated by Django 5.2.3 on 2025-08-04 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_passwordresettoken'),
        ('supplies', '0012_update_monthly_demand_verbose_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='b453calculationitem',
            name='actual_order',
        ),
        migrations.RemoveField(
            model_name='b453calculationitem',
            name='monthly_demand',
        ),
        migrations.RemoveField(
            model_name='b453calculationitem',
            name='monthly_net_demand',
        ),
        migrations.RemoveField(
            model_name='b453calculationitem',
            name='usage_per_set',
        ),
        migrations.RemoveField(
            model_name='dynamiccalculationitem',
            name='apr_2025_stock',
        ),
        migrations.RemoveField(
            model_name='dynamiccalculationitem',
            name='aug_2025_demand',
        ),
        migrations.RemoveField(
            model_name='dynamiccalculationitem',
            name='current_stock_0619',
        ),
        migrations.RemoveField(
            model_name='dynamiccalculationitem',
            name='current_stock_0625',
        ),
        migrations.RemoveField(
            model_name='dynamiccalculationitem',
            name='jul_2025_stock',
        ),
        migrations.RemoveField(
            model_name='dynamiccalculationitem',
            name='jul_m01_demand',
        ),
        migrations.RemoveField(
            model_name='dynamiccalculationitem',
            name='jul_m02_demand',
        ),
        migrations.RemoveField(
            model_name='dynamiccalculationitem',
            name='jul_m03_demand',
        ),
        migrations.RemoveField(
            model_name='dynamiccalculationitem',
            name='jul_m04_demand',
        ),
        migrations.RemoveField(
            model_name='dynamiccalculationitem',
            name='jun_2025_demand',
        ),
        migrations.RemoveField(
            model_name='dynamiccalculationitem',
            name='jun_2025_stock',
        ),
        migrations.RemoveField(
            model_name='dynamiccalculationitem',
            name='may_2025_demand',
        ),
        migrations.RemoveField(
            model_name='dynamiccalculationitem',
            name='may_2025_stock',
        ),
        migrations.AddField(
            model_name='b453calculationitem',
            name='actual_stock',
            field=models.IntegerField(default=0, verbose_name='實際庫存數量'),
        ),
        migrations.AddField(
            model_name='b453calculationitem',
            name='max_total_stock',
            field=models.IntegerField(default=0, verbose_name='最高庫存總數'),
        ),
        migrations.AddField(
            model_name='b453calculationitem',
            name='min_total_stock',
            field=models.IntegerField(default=0, verbose_name='最低庫存總數'),
        ),
        migrations.AddField(
            model_name='b453calculationitem',
            name='monthly_demand_per_station',
            field=models.IntegerField(default=0, verbose_name='当月需求/站'),
        ),
        migrations.AddField(
            model_name='b453calculationitem',
            name='monthly_total_demand',
            field=models.IntegerField(default=0, verbose_name='当月總需求'),
        ),
        migrations.AddField(
            model_name='b453calculationitem',
            name='usage_per_machine',
            field=models.IntegerField(default=0, verbose_name='每台机用量'),
        ),
        migrations.AddField(
            model_name='b453supplyitem',
            name='weekly_demand',
            field=models.JSONField(blank=True, default=dict, verbose_name='各月周需求'),
        ),
        migrations.AddField(
            model_name='dynamiccalculationitem',
            name='chase_data',
            field=models.JSONField(default=dict, verbose_name='追料需求明细'),
        ),
        migrations.AddField(
            model_name='dynamiccalculationitem',
            name='is_multi_station',
            field=models.BooleanField(default=False, verbose_name='是否使用多站别模式'),
        ),
        migrations.AddField(
            model_name='dynamiccalculationitem',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='是否可见'),
        ),
        migrations.AddField(
            model_name='dynamiccalculationitem',
            name='max_total_stock',
            field=models.IntegerField(default=0, verbose_name='最高库存总数'),
        ),
        migrations.AddField(
            model_name='dynamiccalculationitem',
            name='monthly_data',
            field=models.JSONField(default=dict, verbose_name='月度库存和需求明细'),
        ),
        migrations.AddField(
            model_name='dynamiccalculationitem',
            name='multi_station_data',
            field=models.JSONField(default=dict, verbose_name='多使用站别数据'),
        ),
        migrations.AddField(
            model_name='dynamiccalculationitem',
            name='stock_snapshots',
            field=models.JSONField(default=dict, verbose_name='特定日期库存快照'),
        ),
        migrations.AlterField(
            model_name='andorsupplyitem',
            name='monthly_demand',
            field=models.IntegerField(verbose_name='当月需求/站'),
        ),
        migrations.AlterField(
            model_name='b453calculationitem',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.userprofile', verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='b453calculationitem',
            name='material_name',
            field=models.TextField(verbose_name='料件名稱'),
        ),
        migrations.AlterField(
            model_name='b453calculationitem',
            name='max_stock',
            field=models.IntegerField(default=0, verbose_name='最高庫存數'),
        ),
        migrations.AlterField(
            model_name='b453calculationitem',
            name='min_stock',
            field=models.IntegerField(default=0, verbose_name='最低庫存數'),
        ),
        migrations.AlterField(
            model_name='b453calculationitem',
            name='monthly_capacity',
            field=models.IntegerField(default=0, verbose_name='当月產能'),
        ),
        migrations.AlterField(
            model_name='b453calculationitem',
            name='moq_remark',
            field=models.TextField(blank=True, verbose_name='備註(MOQ)'),
        ),
        migrations.AlterField(
            model_name='b453calculationitem',
            name='usage_count',
            field=models.IntegerField(default=0, verbose_name='使用次數'),
        ),
        migrations.AlterField(
            model_name='b453calculationitem',
            name='usage_station',
            field=models.CharField(max_length=50, verbose_name='使用站別'),
        ),
        migrations.AlterField(
            model_name='dynamiccalculationitem',
            name='actual_order',
            field=models.IntegerField(default=0, verbose_name='实际订购数量'),
        ),
        migrations.AlterField(
            model_name='dynamiccalculationitem',
            name='material_name',
            field=models.CharField(default='', max_length=200, verbose_name='料材名称'),
        ),
        migrations.AlterField(
            model_name='dynamiccalculationitem',
            name='max_stock',
            field=models.IntegerField(default=0, verbose_name='最高库存数量'),
        ),
        migrations.AlterField(
            model_name='dynamiccalculationitem',
            name='min_stock',
            field=models.IntegerField(default=0, verbose_name='最低库存数量'),
        ),
        migrations.AlterField(
            model_name='dynamiccalculationitem',
            name='monthly_capacity',
            field=models.IntegerField(default=0, verbose_name='当月产能'),
        ),
        migrations.AlterField(
            model_name='dynamiccalculationitem',
            name='monthly_demand',
            field=models.IntegerField(default=0, verbose_name='当月需求/站'),
        ),
        migrations.AlterField(
            model_name='dynamiccalculationitem',
            name='monthly_net_demand',
            field=models.IntegerField(default=0, verbose_name='当月总需求'),
        ),
        migrations.AlterField(
            model_name='dynamiccalculationitem',
            name='usage_count',
            field=models.IntegerField(default=0, verbose_name='使用次数'),
        ),
        migrations.AlterField(
            model_name='dynamiccalculationitem',
            name='usage_per_set',
            field=models.IntegerField(default=0, verbose_name='每臺機用量'),
        ),
        migrations.AlterField(
            model_name='dynamiccalculationitem',
            name='usage_station',
            field=models.CharField(default='', max_length=100, verbose_name='使用站别'),
        ),
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='导入时间')),
                ('file_name', models.CharField(max_length=255, verbose_name='文件名')),
                ('result', models.TextField(verbose_name='导入结果')),
                ('success', models.BooleanField(default=True, verbose_name='是否成功')),
                ('imported_count', models.IntegerField(default=0, verbose_name='导入数量')),
                ('error_count', models.IntegerField(default=0, verbose_name='错误数量')),
                ('error_details', models.TextField(blank=True, verbose_name='错误详情')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作用户')),
            ],
            options={
                'verbose_name': '导入日志',
                'verbose_name_plural': '导入日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
