# Generated by Django 5.2.3 on 2025-08-05 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0013_add_max_total_stock_field'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE supplies_dynamiccalculationitem ADD COLUMN max_total_stock INTEGER DEFAULT 0;",
            reverse_sql="ALTER TABLE supplies_dynamiccalculationitem DROP COLUMN max_total_stock;"
        ),
    ]
