# Generated by Django 5.2.3 on 2025-08-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0014_add_max_total_stock_field_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamiccalculationitem',
            name='max_total_stock',
            field=models.IntegerField(default=0, verbose_name='最高庫存總數'),
        ),
    ]
