# Generated by Django 5.2.3 on 2025-08-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0015_add_min_total_stock_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamiccalculationitem',
            name='min_total_stock',
            field=models.IntegerField(default=0, verbose_name='最低庫存總數'),
        ),
    ]
